### ISSUE TITLE
closing whodis via hotkey with cursor in .cc window while whodis is open doesn't work if whodis has a smaller window number than the .cc window

### ISSUE THREAD

**Issue by nico** [sgraham/whodis#3]
This fixes it for me (I'd send you a PR but I didn't make a new branch for my other PR); I'm not sure if vim has more stable window IDs that would make this less hacky.

    diff --git a/plugin/whodis.vim b/plugin/whodis.vim
    index 8a4cb48..1f78d31 100644
    --- a/plugin/whodis.vim
    +++ b/plugin/whodis.vim
    @@ -253,6 +253,10 @@ def CloseWhodis():
       vim.command(str(scratch_window_number) + 'wincmd w')
       vim.command('bd')
       if scratch_window_number != original_window_number:
    +    if scratch_window_number < original_window_number:
    +      # If the whodis window was left of the original window, closing its
    +      # window via bd above decreased the original window's window number by 1.
    +      original_window_number -= 1
         vim.command(str(original_window_number) + 'wincmd w')
       vim.command('syn on')
       vim.command('map <silent> %s :python Whodis()<cr>' % vim.eval('WhodisKey'))

**Comment by sgraham** [comment]
I think I might have fixed this with https://github.com/sgraham/whodis/commit/0c5948f124d407c1dadc847cc3b369587e6e263b. Maybe. Possibly.
